train_file: ['construction_dataset/revised_captions_ACID_train.json',
             'construction_dataset/revised_captions_SAFE_train.json',
             'construction_dataset/revised_captions_ACTV_train.json']
val_file_1: ['construction_dataset/revised_captions_ACID_val.json']
val_file_2: ['construction_dataset/revised_captions_SAFE_val.json']
val_file_3: ['construction_dataset/revised_captions_ACTV_val.json']
val_file_4: ['construction_dataset/revised_captions_ACID_val.json',
             'construction_dataset/revised_captions_SAFE_val.json',
             'construction_dataset/revised_captions_ACTV_val.json']

read_local_data: True

coco_root_train: ['construction_dataset/ACID/trainval/', 'construction_dataset/SAFE/', 'construction_dataset/ACTV/']
coco_root_val_1: ['construction_dataset/ACID/trainval/']
coco_root_val_2: ['construction_dataset/SAFE/']
coco_root_val_3: ['construction_dataset/ACTV/']
coco_root_val_4: ['construction_dataset/ACID/trainval/', 'construction_dataset/SAFE/', 'construction_dataset/ACTV/']

bert_config: 'configs/config_bert_stride3.json'

image_res: 384
batch_size_train: 64
vision_width: 768
distill: True
clip_name: "ViT-B-16"
batch_size_test: 64 
k_test: 128

alpha: 0.4
warm_up: True

eos: '[SEP]'
bos: '[CLS]'
prompt: ''

optimizer: {opt: adamW, lr1: 1e-5, lr2: 5e-6, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-5, epochs: 20, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}
use_checkpoint: True
